version: '3.8'
services:
  backend:
    build: ../backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - kafka
      - zookeeper
  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "5432:5432"
  redis:
    image: redis:6
    ports:
      - "6379:6379"
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      ZOO_ENABLE_AUTH: "no"
    ports:
      - "2181:2181"
  kafka:
    image: bitnami/kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9092:9092"