[package]
name = "mini-datadog-backend"
version = "0.1.0"
edition = "2021"
default-run = "mini-datadog-backend"

[dependencies]
axum = { version = "0.7", features = ["ws"] }
tokio = { version = "1.0", features = ["full"] }
tower-http = { version = "0.5", features = ["cors"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
sqlx = { version = "0.7", features = ["runtime-tokio-native-tls", "postgres", "chrono", "json"] }
anyhow = "1.0"
rand = "0.8"
tokio-postgres = "0.7"
reqwest = { version = "0.11", features = ["json"] }
uuid = { version = "1.0", features = ["v4", "serde"] }

[dev-dependencies]

[[bin]]
name = "generate_metrics"
path = "src/bin/generate_metrics.rs"

[[bin]]
name = "generate_aws_data"
path = "src/bin/generate_aws_data.rs"

[[bin]]
name = "mini-datadog-backend"
path = "src/main.rs"